# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebac323126c4fb2ec9a422a025ac5ec5d95d27904c06e2fcd47609afcea37c922d70587b2de8d0c3fe31ef36ba6716ec4d2a74176ae14e363777ee0bc4e1f4cd

test:
  secret_key_base: 993cfe8c4d89994208ce3e4a0ce4c54440e8f43cbe86085118ff26f5bc0fbac50bc71d7d5fd4fa55fb0d12ced185a6c874a5fe728029a57fe789507790a4d883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
